ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS spotify_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS spotify_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS youtube_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS youtube_enabled BOOLEAN NOT NULL DEFAULT FALSE;
