ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS instagram_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS instagram_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS tiktok_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tiktok_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS youtube_social_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS youtube_social_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE profile_links
  ADD COLUMN IF NOT EXISTS section_title TEXT NOT NULL DEFAULT '';
